baseURL = 'https://fisharefriends.org/'
title = 'fish are friends'
timeZone = 'America/Vancouver'
capitalizeListTitles = false
disableKinds = ['taxonomy']

[taxonomies]
category = 'categories'

[markup.goldmark.renderer]
unsafe = true

[module.hugoVersion]
min = '0.146.0'

[params]
author = 'critty'
email = 'critty@fisharefriends.org'
signup = 'https://script.google.com/macros/s/AKfycbx4_QPAM9AQnIfD8QtnuWdZJgYkNLEla_AJtjgrlUJJ_Pu4q_gHgVZ0Ey3dX426zPyGSw/exec'
licence = 'https://www2.gov.bc.ca/gov/content/sports-culture/recreation/fishing-hunting/fishing/recreational-freshwater-fishing-licence'
order = ['journal', 'trips', 'water', 'fish', 'friends', 'music', 'works', 'contact']

[params.tags]
fishies = 'fish'
boat = ''
'non-fish' = ''
'not-fly-fishing' = ''

[params.hues]
trips = 130
fish = 275
friends = 30
music = 355
water = 215
journal = 48
contact = 178
works = 90

[params.waters]
Toquaht = 'Toquaht Estuary'
Ucluelet = 'Ucluelet Harbour'
Squamish = 'Squamish River'

[params.trips.raft]
label = 'raft fishing'
spots = 3

[params.trips.wade]
label = 'walk and wade to learn the basics'
spots = 4
